### PR TITLE
interp-mc: fix step function so that it could be used multiple times

### PR DESCRIPTION
**Pull request by ahmed-irfan**

### CODE REVIEW

**Comment by makaimann** [comment]
Looks like it fails a test in `test_engines`. I think `R` should still be initialized somewhere.

**Comment by ahmed-irfan** [comment]
`R_` is initialized here https://github.com/upscale-project/pono/blob/022e37169a805c7f79f21ed571bb69f14f081ca9/engines/interpolantmc.cpp#L77

**Comment by makaimann** [comment]
Ahh okay. Just pulled the branch and ran the test locally -- it's unsound. It's because `R_` needs to be re-initialized to `init0_` every time the bound is extended.

**Comment by ahmed-irfan** [comment]
i see. I thought we could use the previous over-approximation in the next run. Therefore, closing this PR

**Comment by makaimann** [comment]
Ahh yeah, unfortunately not. The over-approximation is only for the current unrolling.

**Pull request closed without merging**
