### PR TITLE
Rename to pono

### PR DESCRIPTION
**Pull request by makaimann**
The repository has already been renamed pono. This PR would rename all variations of "Cosa2"/"Cosa" to "Pono" in the codebase.

FYI @zhanghongce, @yangy96, @eshan-singh, @leonardt, @clairexen,
we're renaming cosa2 to "pono".

### CODE REVIEW

**Comment by ahmed-irfan** [comment]
just to be sure, are we going to write `Pono` or `pono`?

**Comment by makaimann** [comment]
Haha that's a good question... I'm not picky. I like `pono` for the binary, but if we're referring to the tool it's fine to capitalize. What do you all think?

Also, Travis is failing in the Mac builds now. It looks like it's just failing to set up the environment correctly which happens sometimes. Let's just wait for now and if it fails when I restart it later, I'll look into it more.

**Comment by lonsing** [comment]
>  I like `pono` for the binary, but if we're referring to the tool it's fine to capitalize.

I agree.

**Comment by ahmed-irfan** [comment]
So, it means in the text we should use `Pono` (for example in the AUTHORS file)

**Pull request merged**
