### PR TITLE
cegar and cegar-proph template

### PR DESCRIPTION
**Pull request by ahmed-irfan**
This PR makes the CEGAR and CEGAR-Proph into template classes.

### CODE REVIEW

**Comment by ahmed-irfan** [comment]
@makaimann note that I changed the unroller in the prover.h to be an adaptive-unroller.

We can later make the adaptive unroller the default unroller and remove the old unroller.

**Review by makaimann — APPROVED** [review]
LGTM, thanks for the incremental PRs! Very basic question, why do you need to use `super::*`?

**Comment by makaimann** [comment]
> @makaimann note that I changed the unroller in the prover.h to be an adaptive-unroller.
> 
> We can later make the adaptive unroller the default unroller and remove the old unroller.

Sounds good, I think it makes sense to make the default unroller "adaptive".

**Comment by ahmed-irfan** [comment]
> LGTM, thanks for the incremental PRs! Very basic question, why do you need to use `super::*`?

It is a template thing. Notice that the data members are non-depdendent, so we can also do `this->` or `using`. 
What is your preference?

**Comment by makaimann** [comment]
> It is a template thing. Notice that the data members are non-depdendent, so we can also do `this->` or `using`.
> What is your preference?

I don't feel strongly. Unless you prefer one of the others, I say sticking with `super::` is fine

**Pull request merged**
