### PR TITLE
Add property in get_frame_term

### PR DESCRIPTION
**Pull request by makaimann**
@zhanghongce thanks for catching this

### CODE REVIEW

**Comment by makaimann** [comment]
Wait, I jumped the gun. Let me check a few things first.

**Comment by makaimann** [comment]
All right, I think it's good to go.

**Comment by ahmed-irfan** [comment]
is it a fix or an enhancement? I think it is the latter

**Review by ahmed-irfan — APPROVED** [review]

**Comment by makaimann** [comment]
So I think it's actually a fix -- see here: https://github.com/upscale-project/pono/pull/194#issuecomment-761337288

Basically anything that uses the frame directly needs to have the property in it. I know that the frames are supposed to imply the property, but because we're always assuming the property, it's actually part of the frame. I.e. the frame starts as `P` and we add more clauses onto it so that there's no transition to bad. It's technically possible that `get_frame_term` would return something which doesn't imply `P` before this fix.

**Pull request merged**
