### PR TITLE
fix reset solver in ic3ia

### PR DESCRIPTION
**Pull request by ahmed-irfan**
I had to make some changes in implicit_abstractor and few other changes in the ic3ia code

### CODE REVIEW

**Comment by makaimann** [comment]
I'm not sure I follow this fix. In what situation would there be predicates in the abstraction that weren't added through the `ia_`? As long as it's added there then the `trans` is automatically updated and when you reset the solver the predicate abstraction bi-implications are re-added automatically (because they're in `trans`)

**Comment by ahmed-irfan** [comment]
> I'm not sure I follow this fix. In what situation would there be predicates in the abstraction that weren't added through the `ia_`? As long as it's added there then the `trans` is automatically updated and when you reset the solver the predicate abstraction bi-implications are re-added automatically (because they're in `trans`). Before the reset, it only needs to add the assumption to `trans_label_` because that isn't updated when we updated `trans`.

Right! 
I guess this PR is a side-effect of working late ;-)

**Comment by ahmed-irfan** [comment]
Not needed after clarification

**Comment by makaimann** [comment]
I can add a comment somewhere that makes this clearer though -- it's definitely subtle.

**Pull request closed without merging**
