### PR TITLE
Use default inductive_generalization for option 0 in mbic3

### PR DESCRIPTION
**Pull request by makaimann**

### CODE REVIEW

**Comment by makaimann** [comment]
Hey @ahmed-irfan , this seems to fix https://github.com/upscale-project/pono/issues/225. Although I'm going to look into it more because I don't fully understand what was wrong about the previous implementation. Changing the solver also changed the outcome, but that could just be luck. Let me know if you have any thoughts.

**Comment by makaimann** [comment]
Btw, I think this is a nice change even aside from the bug fix because there's less code duplication.

**Review by ahmed-irfan — APPROVED** [review]
LGTM

deduplication is always appreciated :)

**Comment by makaimann** [comment]
In case you're curious, the issue was here: https://github.com/upscale-project/pono/blob/c6086aa4ac448bb1b5b9858d8a2f203e40cd16c4/engines/mbic3.cpp#L174. The label is actually for `ts_.next(t)` but it's using `label(t)` instead. I think the bug only occurred with `boolector` because of the aggressive rewriting. It seems like in most cases it's fine to use `t` instead of `ts_.next(t)` to get the label here, because they're always dropped together. But due to some rewriting going on, this can actually end up giving the wrong result.

**Pull request merged**
